---
title: "Assignment 3"
author: "Pratishtha Deep"
date: "October 16, 2017"
output: word_document
---
```{r Assignment3 Pratishtha}
#QUE1: Import the data into R.
library(dplyr)
ForestFires = read.csv("C:/Users/pratishtha/Downloads/forestfires.csv", header = TRUE, sep = ',')
head(ForestFires)

#####a. How many observations are there in the dataset?
nrow(ForestFires)

#####b. How many observations are there with a fire (i.e., area>0)
nrow(subset(ForestFires, area>0))

#####c. How many observations are there with a rain (i.e., rain>0)
nrow(subset(ForestFires, rain > 0))

#####d. How many observations are there with both a fire and a rain?
nrow(ForestFires[ForestFires$area>0 & ForestFires$rain>0, ])

#Que2: Show the columns month, day, area of the all the observations.
head(ForestFires[, c('month', 'day', 'area')])


#Que3: Show the columns month, day, area of the observations with a fire.
head(ForestFires[ForestFires$area>0, c('month', 'day', 'area')])

#Que4: How large are the five largest fires (i.e., having largest area)
ForestFires_df<-ForestFires[ForestFires$area>0, ]
ForestFires_arrange <- arrange(ForestFires_df, desc(area))
ForestFire_largest<-(top_n(ForestFires_arrange, 5, area))
ForestFire_largest$area

####a. What are the corresponding month, temp, RH, wind, rain area?
ForestFires_df<-ForestFires[ForestFires$area>0, ]
ForestFires_arrange <- arrange(ForestFires_df, desc(area))
ForestFire_largest<-(top_n(ForestFires_arrange, 5, area))
head(ForestFire_largest)

####b. Reorder factor levels of month to be from Jan to Dec. Add one column to the data indicating whether a fire occurred for each observation (True for area >0 and False for area ==0)
levels(ForestFires$month)
ForestFires$month = factor(ForestFires$month, levels = c('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'))
ForestFires$data<- ifelse(ForestFires$area>0, "TRUE", "FALSE")
head(ForestFires)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
